### ISSUE TITLE
Depreciation Warning?

### ISSUE THREAD

**Issue by johntran** [jxnblk/reflexbox#60]
Seems like https://github.com/jxnblk/grid-styled is being used in favor over `reflexbox`. Is there a reason for `reflexbox` to continue to be used?

**Comment by jxnblk** [comment]
There is a slightly different implementation between the two libraries despite their API similarities. Grid Styled depends on styled-components whereas this library is self-contained. It should still work so you might consider it "feature complete" rather than deprecated. That said styled-components offers a few extra things that Reflexbox does not
