### ISSUE TITLE
more properties?

### ISSUE THREAD

**Issue by contra** [jxnblk/reflexbox#7]
It seems like this only supports a subset of flex-box right now.

Are you open to adding props for the other parts of flexbox? (row, row-reverse, grow, etc.)

If so, I can start sending PRs

**Comment by jxnblk** [comment]
Absolutely. I haven't really touched the API since I started this. Now I'm leaning more towards an API that reflects what's here: https://github.com/basscss/basscss/blob/master/modules/flexbox/index.css

The other aspect I'm considering is how to handle cases where certain styles, like `margin-left: auto` and `width: 100%` really help with flex box layouts, but trying to keep the API limited and 1:1 with the spec.

**Comment by contra** [comment]
Looking for help maintaining this?

**Comment by jxnblk** [comment]
I'm always happy to accept help and/or PRs - still generally trying to explore this space a bit so feel free to ask questions or contribute as much as you want

**Comment by jxnblk** [comment]
Just a heads up if you're working on a PR for changing the props. I'm changing some of how configuration and padding/margin props are handled, so be sure to realign with the latest and keep an eye out for an updated version.

**Comment by contra** [comment]
@jxnblk I'll hold off until that's done, might be a big conflict

**Comment by jgoux** [comment]
I'm not against a `flex: none` property. 👍
